-- phpMyAdmin SQL Dump
-- version 3.4.3.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jun 15, 2014 at 07:13 AM
-- Server version: 5.6.16
-- PHP Version: 5.4.24

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `site_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `about`
--

CREATE TABLE IF NOT EXISTS `about` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(75) NOT NULL,
  `tag` varchar(50) NOT NULL,
  `text` text NOT NULL,
  `link` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;

--
-- Dumping data for table `about`
--

INSERT INTO `about` (`id`, `name`, `tag`, `text`, `link`) VALUES
(1, 'Eyal Kenig', 'eyalk', '<div id="member"><img class="img-circle img-responsive pull-right" src="../img/members/eyal.png" alt="" width="150" height="140" />\r\n<div id="Education">\r\n<h4>Education:</h4>\r\n<ul class="about-ul">\r\n<li>B.Sc. in Computer Science, Ben-Gurion University of the Negev.</li>\r\n</ul>\r\n</div>\r\n<div id="Method-Techniques">\r\n<h4>Methods and Techniques:</h4>\r\n<ul>\r\n<li>Developing languages: C#, WPF, JavaScript, jQuery, CSS3, HTML5.</li>\r\n<li>Databases Use: SQL Server, MySQL.</li>\r\n</ul>\r\n</div>\r\n<div id="Hobbies">\r\n<h4>Hobbies:</h4>\r\n<p>Sports, Music.</p>\r\n</div>\r\n<div id="Contact">\r\n<h4>Contact:</h4>\r\n<p>Mail: <a href="mailto:eyalke@post.bgu.ac.il" target="_top">eyalke@post.bgu.ac.il</a></p>\r\n</div>\r\n<div id="Publications">\r\n<h4>&nbsp;</h4>\r\n<script>// <![CDATA[\r\nfunction PublicationFunc() {\r\n    alert("Sorry, I don''t have Publictions yet.");\r\n}\r\n// ]]></script>\r\n</div>\r\n</div>', NULL),
(2, 'Alexander Shknevsky', 'alexs', '<p><img class="img-circle img-responsive pull-right" src="../img/members/alexs.jpg" alt="" width="150" height="140" /></p>\r\n<div id="Education">\r\n<h4>Education:</h4>\r\n<ul class="about-ul">\r\n<li>M.Sc Information systems Eng.</li>\r\n<li>B.Sc. in Software Engineering, Ben-Gurion University of the Negev.</li>\r\n</ul>\r\n</div>\r\n<div id=" Research-area">\r\n<h4>Research area:</h4>\r\n<ul class="about-ul">\r\n<li>Temporal Data Mining</li>\r\n<li>Machine Learning</li>\r\n<li>Temporal Abstraction</li>\r\n<li>Medical Informatics</li>\r\n</ul>\r\n</div>\r\n<div id="Research-topics">\r\n<h4>Research topics:</h4>\r\n<ul class="about-ul">\r\n<li>Application of temporal data mining methods for the analysis of clinical data</li>\r\n</ul>\r\n</div>\r\n<div id="Method-Techniques">\r\n<h4>Methods and Techniques:</h4>\r\n<ul>\r\n<li>Developing languages: C#, Java, Java Script.</li>\r\n<li>Databases Use: MSSQL, Oracle, MS Access, MySQL, MongoDB.</li>\r\n<li>Technologies: ASP.Net, WPF, WCF, Parallel computing.</li>\r\n<li>Servers: AD, IIS, Exchange, MSSQL Server.</li>\r\n</ul>\r\n</div>\r\n<div id="Hobbies">\r\n<h4>Hobbies:</h4>\r\n<p>Traveling, Sports.</p>\r\n</div>\r\n<div id="Contact">\r\n<h4>Contact:</h4>\r\n<p>Mail: <a href="mailto:sheknabs@post.bgu.ac.il" target="_top">sheknabs@post.bgu.ac.il</a></p>\r\n</div>', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `members`
--

CREATE TABLE IF NOT EXISTS `members` (
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `members`
--

INSERT INTO `members` (`username`, `password`) VALUES
('admin', 'admin');

-- --------------------------------------------------------

--
-- Table structure for table `Publications`
--

CREATE TABLE IF NOT EXISTS `Publications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tag` varchar(250) NOT NULL,
  `title` varchar(700) NOT NULL,
  `abstract` text NOT NULL,
  `link` varchar(250) DEFAULT NULL,
  `name` varchar(250) NOT NULL,
  `year` varchar(50) DEFAULT NULL,
  `subject` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tag` (`tag`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=35 ;

--
-- Dumping data for table `Publications`
--

INSERT INTO `Publications` (`id`, `tag`, `title`, `abstract`, `link`, `name`, `year`, `subject`) VALUES
(1, 'ayelet', 'a framework for automated knowledge- based textual summarization of longitudinal medical record', '    Goldstein, A., and Shahar, Y. (2012). A framework for automated knowledge-\r\nbased textual summarization of longitudinal medical records. Proceedings of the 4th international workshop on knowledge representation for health care (KR4HC''12), Tallinn, Estonia.', '', 'Ayelet Goldstien', NULL, NULL),
(2, 'ayelet', 'Implementation of a System for Intelligent Summarization of Longitudinal Clinical Records.', 'Goldstein, A., and Shahar, Y. (2013). Implementation of a System for Intelligent Summarization of Longitudinal Clinical Records. Proceedings of the 5 international workshop on knowledge representation for health care (KR4HC''13), in conjunction with Artificial Intelligence in Medicine (AIME-2013), Murcia, Spain. ( also published in Process Support and Knowledge Representation in Health Care Lecture Notes in Computer Science Volume 8268, 2013, pp 68-82, D. Riano, R. Lenz, S.Miksch, M. Peleg, M. Reichert, A.Teije, Springer International Publishing, 2013. )', NULL, 'Ayelet Goldstien', NULL, NULL),
(5, 'erez', '*Hatsek, A., Young, O., Shalom, E., and Shahar, Y.  (2006). A demonstration of DeGeL: A clinical-guidelines library and automated guideline-support tools.  Proceedings of The Workshop on AI techniques in healthcare: Evidence-based guidelines and protocols, in conjunction with The 17th biennial European Conference on Artificial Intelligence (ECAI-2006), Riva del Garda (Trento), Italy.', 'not available', NULL, 'Erez Shalom', '2006', 'Conference and Workshop Proceedings'),
(7, 'erez', '* Shalom, E., Shahar, Y., Lunenfeld, E., Taieb-Miamon, M., Young, O., Bar, G., Martins, S.B, Vaszar, L., Liel, Y., Yarkoni, A., Goldstein, M.K., Leibovitz, A., and Marom, T.  (2006). The importance of creating an ontology-specific consensus before a markup-based specification of clinical guidelines. Proceedings of The Workshop on AI techniques in healthcare: Evidence-based guidelines and protocols, in conjunction with The 17th biennial European Conference on Artificial Intelligence (ECAI-2006), Riva del Garda (Trento), Italy.', 'We have previously developed the Digital electronic Guideline Library (DeGeL) framework, which includes a methodology for a markup-based, increasingly formal structuring of free-text clinical guidelines (GLs), and tools to support guideline-based application. The methodology includes activities be-fore, during and after the markup process. To reduce the ambiguity of the interpretation of a GL among the Expert Physicians (EPs) who are marking up the GL, and to achieve an interpretation common to the EPs and the knowledge engineers (KEs), an indispensable step before markup is the creation of an Ontology Specific Consensus (OSC) regarding the semantics of the GL. To evaluate the role of the OSC, we created OSCs for three GLs in incremental level of de-tail, using the Asbru GL ontology. The EPs quantified the subjective aspects that most helped them in creating the OSC, while we assessed the clinical and ontological markup errors committed by the EPs. Using medical knowledge and understanding the GL ontology were considered more helpful than understanding the DeGeL tools; and the more detailed the OSC, the less the number of markup errors committed.', 'Publications/ErezShalom/The Importance of Creating an Ontology-Specific Consensus Before a Markup-Based Specification of Clinical Guidelines.pdf', 'Erez Shalom', '2006', 'Conference and Workshop Proceedings'),
(8, 'erez', '*Hatsek, A., Young, O., Shalom, E., and Shahar, Y. (2008). DeGeL: A clinical-guidelines library and automated guideline-support tools. In Ten-Teije, A., Miksch, S., and Lucas, P. (eds), Computer-based medical guidelines and protocols: A primer and current trends. Vol. 139 of Studies in Health technology and Informatics, IOS press, Amsterdam, pp 203-212.', ' Using machine-interpretable clinical guidelines to support evidence-based medicine promotes the quality of medical care. In this paper, we present the Digital Electronic Guidelines Library (DeGeL), a comprehensive framework, including a Web-based guideline repository and a suite of tools, to support the use of automated guidelines for medical care, research, and quality assessment. Recently, we have developed a new version (DeGeL.NET) of the digital library and of its different tools. We intend to present a brief up to-date explanation of a Digital Library for GLs that we had developed. We explain how it assists physicians and knowledge engineers in acquisition and representation of the GLs knowledge and how it assists users in searching, retrieving, and applying a relevant GL in a manner customized to each patient.\r\nIn order to support the automation of guideline-based care, there is a need to convert the GL from its free-text representation into a machine interpretable format. The guiding principle followed in our research is specifying GLs through the collaboration between expert physicians (EPs), clinical editors (CEs),(i.e. physicians who are not necessarily experts in the GL medical domain, but are familiar with the semantics of the representation format, known also as the GL ontology), and knowledge engineers (KEs). EPs and CEs transform the clinical knowledge represented in free text GLs into intermediate, semantically meaningful representations while KEs convert these intermediate representations into a formal, machine-interpretable representation.\r\n', 'Publications/ErezShalom/DeGeL- A Clinical-Guidelines Library and Automated Guideline-Support Tools.pdf', 'Erez Shalom', '2008', 'Collective Volumes'),
(9, 'erez', 'Shalom E, Fridman I, Shahar Y, Hatsek A & Lunenfeld E. Towards a realistic clinical-guidelines application framework: desiderata, applications, and lessons learned. LNCS 7738: Process Support and Knowledge Representation in Healthcare.2013:56-70', 'not available', NULL, 'Erez Shalom', '2013', 'Collective Volumes'),
(10, 'erez', '*Shahar Y, Young O., Shalom E., Mayaffit A., Moskovitch R., Hessing A., and Galperin M. (2003).  DEGEL: A hybrid, multiple-ontology framework for specification and retrieval of clinical guidelines.  Proceedings of the 9th Conference on Artificial Intelligence in Medicine Europe (AIME  03), pp. 122-130, Protaras, Cyprus', ' not available', '', 'Erez Shalom', '2003', 'Conference and Workshop Proceedings'),
(11, 'erez', '*Shahar Y, Shalom E., Mayaffit A., Young O., Galperin M., Martins S.B., and Goldstein, M.K. (2003).  A distributed, collaborative, structuring model for a clinical-guideline digital-library.  Proceedings of the 2003 AMIA Annual Fall Symposium, Washington, DC. ', 'not available', NULL, 'Erez Shalom', '2003', 'Conference and Workshop Proceedings'),
(12, 'erez', '* Shalom, E., and Shahar, Y. (2005).  A graphical framework for specification of clinical guidelines at multiple representation levels.  Proceedings of the 2005 AMIA Annual Fall Symposium, Washington, DC. ', 'not available', NULL, 'Erez Shalom', '2005', 'Conference and Workshop Proceedings'),
(13, 'erez', '* Shalom E, Shahar, Y., Taieb-Maimon M., Bar, G., Martins S.B., Young, O., Vasar, L.T., Liel, Y.,  Yarkoni, A., Goldstein, M.K., Leibowitz, A., Marom, T., and Lunenfeld, E. (2008). Can physicians structure clinical guidelines?  experiments with a mark-up-process methodology. Proceedings of the Workshop on Knowledge Management for Healthcare Processes, ECAI 2008, the 18th European Conference on Artificial Intelligence, Patras, Greece. ', 'not available', NULL, 'Erez Shalom', '2008', 'Conference and Workshop Proceedings'),
(14, 'erez', '* Hatsek, A., Shahar, Y., Taieb-Maimon, M.,  Shalom, E.,  Dubi-Sobol, A.,  Bar, G.,  Koyfman, A.,  and Lunenfeld, E. (2008). A methodological specification of a guideline for diagnosis and management of preeclampsia. Proceedings of the Workshop on Knowledge Management for Healthcare Processes, ECAI 2008, the 18th European Conference on Artificial Intelligence, Patras, Greece.', 'not available', NULL, 'Erez Shalom', '2008', 'Conference and Workshop Proceedings'),
(15, 'erez', '* Shalom E, Hatsek A, Shahar Y , Kaufman G.(2009). System Demonstration: A Prototype for Automatic Application of A Guideline for Chronic Heart Failure Patients. Workshop on Knowledge Representation for Healthcare (KRHC), in conjunction with the 13th Conference on Artificial Intelligence in Medicine (AIME) Verona, Italy', 'not available', NULL, 'Erez Shalom', '2009', 'Conference and Workshop Proceedings'),
(16, 'erez', '*Shalom, E., Friedman, I., Shahar, Y., Hatsek, A., and Lunenfeld, E. (2011). Towards a realistic clinical-guidelines application framework: Desiderata, Applications, and lessons learned. Proceedings of the 3th international workshop on knowledge representation for health care (KR4HC''11), Bled, Slovenia.', ' Clinicians can benefit from automated support to guideline (GL) application at the point of care. However, several conceptual dimensions should be considered for a realistic application: 1) The representation of the knowledge might be through structured text (semi-formal), or specified in a machine- comprehensible language (formal); 2) The availability of electronic patient data might be partial or full; 3) GL-based recommendations might be triggered by a human-initiated (synchronous) session, or data driven (asynchronous). In addition, several requirements must be fulfilled, such as an evaluation of the GL application engine by a GL simulation engine. Finally, to apply multiple GLs, by multiple users, in multiple settings, the GL-application engine should be designed as an enterprise architecture that can plug into any Electronic Medical Record (EMR). We present an architecture fulfilling these desiderata, describe application examples with different conceptual dimensions and requirements, using our new GL-application engine, PICARD, discuss lessons learned, and briefly describe a clinical evaluation of the current framework in the domain of pre-eclampsia/toxemia of pregnancy.\r\n', 'Publications/ErezShalom/Erez.shalom.KRHC.Final-P1.pdf', 'Erez Shalom', '2011', 'Conference and Workshop Proceedings'),
(17, 'erez', '*Friedman, I., Shalom, E., and Shahar, Y. (2011). Evaluation of guideline-application engines by longitudinal simulation: A Position Paper. Proceedings of the 3th international workshop on knowledge representation for health care (KR4HC''11), Bled, Slovenia.', 'not available', NULL, 'Erez Shalom', '2011', 'Conference and Workshop Proceedings'),
(18, 'erez', 'Topaz M, Shalom E, Masterson-Creber R, Radhakrishnan K & Bowles KH. (2013). Podium presentation: Generating Nursing Specific, Time-Oriented, Hierarchical Computer Interpretable Guidelines: Tools Used and Lessons Learned. First International Conference on Research Methods for Standardized Terminologies (Eagan, MN).', 'not available', NULL, 'Erez Shalom', '2013', 'Conference and Workshop Proceedings'),
(19, 'erez', 'Sacchi L, Fux A, Napolitano C, Panzarasaa S, Peleg M, Quaglini S, Shalom E, Soffer P, Tormene P. (2013). Patient-tailored Workflow Patterns from Clinical Practice Guidelines Recommendations. Medinfo 2013 ', ' MobiGuide is a project devoted to the development of a pa- tient-centric decision support system based on computerized clinical guidelines for chronic illnesses including Atrial Fi- brillation (AF). In this paper we describe the process of (1) identifying guideline recommendations that will require pa- tients to take actions (e.g., take measurement, take drug), thus impacting patients daily-life behavior, (2) eliciting from the medical experts the corresponding set of personalized opera- tionalized advices that are not explicitly written in the guide- line (patient-tailored workflow patterns) and (3) delivering this advice to patients. The analysis of the AF guideline has resulted in four types of patient-tailored workflow patterns: therapy-related advisors, measurements advisors, suggestions for dealing with interventions that may require modulating patient therapy, and personalized packages for close monitor- ing of patients. We will show how these patterns can be gen- erated using information stored in a patient health record that embeds clinical data and data about the patients personal context and preferences.', 'Publications/ErezShalom/Patient-tailored Workflow Patterns from Clinical Practice Guidelines Recommendations.pdf', 'Erez Shalom', '2013', 'Conference and Workshop Proceedings'),
(20, 'erez', 'Peleg M, Broens T, Gonzlez-Ferrer E, Shalom E. Architecture for a Ubiquitous Context-aware Clinical Guidance System for Patients and Care Providers Proceedings of the 4th international workshop on knowledge representation for health care (KR4HC''13), Murcia, Spain.', ' not available', '', 'Erez Shalom', '', 'Conference and Workshop Proceedings'),
(21, 'erez', 'Shalom E., Shahar Y, Lunenfeld E (2013). Clinical decision support through the automated application of clinical guidelines Proceedings of the 7th ILAIS Conference, July 1, 2013, Ruppin Academic Center, Emek Hefer, Israel 153-158 ', 'not available', NULL, 'Erez Shalom', '2013', 'Conference and Workshop Proceedings'),
(22, 'erez', 'Arturo Gonzlez-Ferrer, Mor Peleg, Enea Parimbelli, Erez Shalom, Carlos Marcos Lagunar, Guy Klebanov, Iaki Martnez-Sarriegui, Nick Lik San Fung, Tom Broens. ', ' not available', '', 'Erez Shalom', '2014', 'Conference and Workshop Proceedings'),
(23, 'erez', '* Shahar Y, Young O., Shalom E., Mayaffit A., Moskovitch R., Hessing A., and Galperin M. (2004). A hybrid, multiple-ontology framework for specification and retrieval of clinical guidelines. The Journal of Biomedical Informatics 37(5), 325-344.', 'clinical guidelines are a major tool in improving the quality of medical care. \r\nHowever, most guideline are in free text, not in formal, executable format, and are not easily accessible to clinicians at the point of care. We introduce a Web-base, modular, distributed architecture, the Digital Electronic Guideline Library (DeGeL), which facilitates gradual conversion of clinical guideline from text to a formal representation in chosen target guideline ontology. The architecture supports guideline classification, semantic markup, context-sensitive search, browsing, run-time application, and retrospective quality assessment. The DeGeL hybrid meta-ontology  include elements common to all guideline ontologies, such as semantic classification and domain knowledge; it also includes four content-representation, and a formal representation. These formats support increasingly sophisticated computational tasks. The DeGeL tools for support of guideline-based care operate, at some level, on all guideline ontologies. We have demonstrated the feasibility of the architecture and the tools for several guideline ontologies, include Asbru and GEM', 'Publications/ErezShalom/A hybrid, multiple-ontology framework for specification and retrieval of clinical guidelines.pdf', 'Erez Shalom', '2007', 'Press in Scientific Journals'),
(24, 'erez', '*Young, O., Shahar, Y., Lunenfeld, E., Liel Y., Bar, G., Shalom, E., Martins S.B., Vaszar, L.T., Marom, T., and Goldstein, M.K. (2007). Runtime application of hybrid-Asbru clinical guidelines. The Journal of BioMedical Informatics 40, 507–526. 	[Impact factor:  ISI – 2.0 (2007)]', 'not available', NULL, 'Erez Shalom', '2007', 'Press in Scientific Journals'),
(25, 'erez', '*Shalom E, Shahar, Y., Taieb-Maimon M., Lunenfeld, E., Bar, G., Yarkoni, A., Young, O., Martins S.B., Vaszar, L.T., Goldstein, M.K., Liel, Y., Leibowitz, A., Marom, T., and Lunenfeld, E. (2008). A quantitative evaluation of a methodology for collaborative specification of clinical guidelines at multiple representation levels. The Journal of BioMedical Informatics 41(6), 889-903.', 'not available', NULL, 'Erez Shalom', '2008', 'Press in Scientific Journals'),
(26, 'erez', '*Shalom E, Shahar, Y., Taieb-Maimon M., Martins S.B., Vaszar, L.T., Goldstein, Gutnik, L., and Lunenfeld, E.  (2009). Ability of expert physicians to structure clinical guidelines: Reality versus perception. Journal of Evaluation in Clinical Practice 15 (2009) 1043–1053. ', 'not available', NULL, 'Erez Shalom', '2007', 'Press in Scientific Journals'),
(27, 'erez', '*Hatsek, A., Shahar, Y., Taieb-Maimon, M., Shalom, E., Klimov, D., and Lunenfeld, E. (2010). A scalable architecture for incremental specification and maintenance of procedural decision-support knowledge. The Open Medical Informatics Journal, 4, 255-277.', 'not available', NULL, 'Erez Shalom', '2010', 'Press in Scientific Journals'),
(28, 'erez', 'Shalom E, Shahar, Y and Lunenfeld, E.  (2013) Automatic application of Clinical Guidelines -  from theory to practice. Harefua journal,152(5) 272-278.', 'not available', NULL, 'Erez Shalom', '2013', 'Press in Scientific Journals'),
(29, 'erez', 'Gema García-Sáez, Mercedes Rigla, Iñaki Martínez-Sarriegui, Erez Shalom, Mor Peleg, Tom Broens, Belén Pons, Estefanía Caballero-Ruíz, Enrique J. Gómez and M. Elena Hernando. “Patient-oriented Computerized Clinical Guidelines for Mobile Decision Support in Gestational Diabetes” Journal of Diabetes Science Technology, published online 6 March 2014 DOI: 10.1177/1932296814526492', 'not available', NULL, 'Erez Shalom', '2014', 'Press in Scientific Journals'),
(30, 'erez', '*Y. Shahar, E. Shalom, O. Young, R. Moskovitch, D. Boaz and M. Galperin , A (2002) Hybrid Framework for Representation and use of Clinical Guidelines. The  American Medical Informatics Association (AMIA), Fall Symposium, Washington, DC ', 'linical guidelines are a powerful method for improving the quality of medical care'', while reducingitscosts. Mostclinicalguidelines,however, aretext-basedandinaccessibletothephysicianswho most need them; in addition, physicians rarely have the time to decide which guideline best pertains to theirpatient,andwhatdoesapplyingthatguidelineto theparticularpatiententail. Thus,thereisanurgent need to automate guideline dissemination and application. There have been multiple eforts to automate guideline-based care. However, converting free-text-based guidelines to a machine-readable format,whilesupportingbothtext-basedsearchand retrieval,aswellasautomatedapplicationandquality assessment,isapressingproblem.\r\n', 'Publications/ErezShalom/A (2002) Hybrid Framework for Representation and use of Clinical Guidelines.pdf', 'Erez Shalom', '2002', 'International Meetings'),
(31, 'erez', '*Shahar, Y, Mayaffit, A, Shalom, E.,. Young, O., Galperin, M., Moskovitch, R., and Hessing, A. (2003).  A multiple-phase platform for representation and use of clinical guidelines.  Proceedings of the 2003 Annual Meeting of the Israeli Medical Informatics Association (ILAMI), Tel Aviv, Israel.', 'not available', NULL, 'Erez Shalom', '2003', 'International Meetings'),
(32, 'erez', '* Shahar, Y, Young, O., Shalom, E., Mayaffit, A., Moskovitch, R., Hessing, A., and Galperin, M. (2004).  The Digital Electronic Guideline Library (DeGeL): A hybrid framework for representation and use of clinical guidelines.  The 2004 Workshop on Clinical Guidelines and Protocols (CGP-2004), Prague, Czech Republic.', 'Using machine-interpretable clinical guidelines to support evidence-based medicine promotes the quality of medical care. In this paper, we present the Digital Electronic Guidelines Library (DeGeL), a comprehensive framework, including a Web-based guideline repository and a suite of tools, to support the use of automated guidelines for medical care, research, and quality assessment. Recently, we have developed a new version (DeGeL.NET) of the digital library and of its different tools. We intend to present a brief up to-date explanation of a Digital Library for GLs that we had developed. We explain how it assists physicians and knowledge engineers in acquisition and representation of the GL’s knowledge and how it assists users in searching, retrieving, and applying a relevant GL in a manner customized to each patient.\r\nIn order to support the automation of guideline-based care, there is a need to convert the GL from its free-text representation into a machine interpretable format. The guiding principle followed in our research is specifying GLs through the collaboration between expert physicians (EPs), clinical editors (CEs),(i.e. physicians who are not necessarily experts in the GL medical domain, but are familiar with the semantics of the representation format, known also as the GL ontology), and knowledge engineers (KEs). EPs and CEs transform the clinical knowledge represented in free text GLs into intermediate, semantically meaningful representations while KEs convert these intermediate representations into a formal, machine-interpretable representation.\r\n', 'Publications/ErezShalom/DeGeL- A Clinical-Guidelines Library and Automated Guideline-Support Tools.pdf', 'Erez Shalom', '2004', 'International Meetings'),
(33, 'erez', '*Shalom E and Shahar Y. (2005). A graphical tool for knowledge acquisition  Proceedings of the 2005 Annual Meeting of the Israeli Medical Informatics Association (ILAMI), Tel Aviv, Israel', 'not available', NULL, 'Erez Shalom', '2005', 'International Meetings'),
(34, 'erez', '*Shalom, E., Shahar, Y., Young, O., Lunenfeld, E., Bar, G., Yarkoni, A., Liel, Y., Taieb-Miamon, M., Lebovitz, A., Marom, T., Martins, S.B, and Vaszar, L. (2006). Are physicians able to structure medical knowledge? A methodology for a quantitative and qualitative evaluation of tools for specification and structuring of clinical guidelines at several levels of representation. Proceedings of the 2006 Annual Meeting of the Israeli Medical Informatics Association (ILAMI), Tel Aviv, Israel.', 'not available', NULL, 'Erez Shalom', '2006', 'International Meetings');

-- --------------------------------------------------------

--
-- Table structure for table `search`
--

CREATE TABLE IF NOT EXISTS `search` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(250) NOT NULL,
  `description` text NOT NULL,
  `keywords` text NOT NULL,
  `link` varchar(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=13 ;

--
-- Dumping data for table `search`
--

INSERT INTO `search` (`id`, `title`, `description`, `keywords`, `link`) VALUES
(7, 'Dr. Erez Shalom', 'Education:\r\nPhd. Student\r\nM.Sc Information systems Eng.\r\nB.Sc\r\nIndustrial Eng.\r\nInformation Systems specialty\r\n\r\nContact:\r\nMail:erezsh@bgu.ac.il\r\n\r\n', 'Dr. Erez Shalom\r\nDesign and development of cloud-based applications, Information Systems Engineering, Ben Gurion University (2013)\r\nCloud-based Mobile applications (Afeka Collage, 201s2-2013)\r\nWeb-based programming, Information Systems Engineering, Ben Gurion University (2008-2013)\r\nWeb-based programming and management, Computer science, Sapir Collage (2007-2013)\r\nIntroduction to information system, Computer science, Sapir Collage (2007-2012)\r\nAdvanced Web-based programming, Information Systems Engineering, Ben Gurion University (2008-2011)\r\nElectronic commerce, Information Systems Engineering, Ben Gurion University (2008)\r\nIntroduction to information system, Information Systems Engineering, Ben Gurion University (2007)\r\nDEGEL (Digital Guidelines Library)\r\nknowledge acquisition of clinical protocols\r\nclinical guidelines application\r\nAsbru\r\nMedical Informatics\r\nMedical Decision Support Systems\r\nWeb programming\r\n', 'Members/ErezS.html'),
(8, 'Ayelet Goldstein', ' Education:\r\nPh.D.	2010-today:	Ben Gurion University  Information System Engineering Advisor: Prof. Yuval Shahar. Research title: Automated Knowledge-Based Textual Summarization System for Time-Oriented Clinical Data\r\nM.Sc Information systems Eng.\r\nB.Sc. in Software Engineering, Ben-Gurion University of the Negev.\r\n\r\nContact:\r\nMail: ayelet.goldstein@gmail.com', ' Ayelet Goldstein\r\nTemporal reasoning\r\ntemporal data summarization\r\nnatural language generation\r\nknowledge-based systems, mostly in biomedical domains\r\n10/2011-Now: Work Package Leader in the 7th Framework European Union program, the Mobiguide Project.\r\nCoordination and leading several academic and industrial European partners.\r\n03/2010-10/2011:	Business Dev. Manager, Iris Ventures Technological Incubator.\r\nEvaluation of new start-ups technologies\r\nManagement of the due-diligence process\r\n06/2003-05/2008:	DBA & Software engineer, Intel, Israel\r\nDevelopment and maintenance of IT systems and applications, Quality Systems, control systems and solution design, support and troubleshooting.\r\nAdministration of SQL and Oracle servers, databases and environments.', 'Members/ayelet.html#ayeletg'),
(9, 'Alexander Shknevsky', 'Education:\r\nM.Sc Information systems Eng.\r\nB.Sc. in Software Engineering, Ben-Gurion University of the Negev.\r\n\r\nContact:\r\nMail: sheknabs@post.bgu.ac.il', 'Alexander Shknevsky\r\nApplication of temporal data mining methods for the analysis of clinical data', 'Members/alex.html#alexs'),
(10, 'Elior Ariel', 'Education:\r\nM.Sc Information systems Eng.\r\nB.Sc. in Software Engineering, Ben-Gurion University of the Negev.\r\n\r\nContact:\r\nMail: eliorar@post.bgu.ac.il', 'Elior Ariel\r\nAI Risk Analysis\r\nCritiquing Systems\r\nQuality Assessment\r\nPlan Recognition', 'Members/elior.html#eliors'),
(11, 'Eyal Kenig', 'Education:\r\nB.Sc. in Computer Science, Ben-Gurion University of the Negev.\r\n\r\nContact:\r\nMail: eyalke@post.bgu.ac.il', 'Eyal Kenig', 'Members/eyal.html#eyalk'),
(12, 'Prof. Yuval Shahar', 'Informationtion Systems Engineering Head, Medical Informatics Research Center Head, Graduate Program, Information Systems Engineering', 'Prof. Yuval Shahar', 'http://www.ise.bgu.ac.il/faculty/shahar/');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
